"use client";

import { useEffect, useState } from "react";

type Status = "Not started" | "Preparing" | "Ready" | "Submitted" | "Interview" | "Closed";
type Opportunity = {
  id: string; title: string; institution: string; country: string;
  deadline: string; deadlineNote: string; opens?: string; start: string;
  timing: "Ideal target" | "Needs confirmation"; mscBy: string; msc: string;
  funding: string; amount?: number; currency?: string; period?: "year" | "month";
  official: string; portal?: string; portalNote?: string;
  fit: string; maths: string; action: string; documents: string[];
  references: string; english: string; verified: string; custom?: boolean;
};
type Progress = { status: Status; notes: string; actionDate: string; checked: Record<string, boolean> };
type Saved = { version: 2; progress: Record<string, Progress>; custom: Opportunity[]; archive: Record<string, unknown>[]; master: Record<string, boolean>; rates: Record<string, number>; rateDate: string };
const KEY = "mayimunah-phd-tracker-v2";
const OLD_KEY = "mayimunah-application-tracker-v1";
const OLD_CHECK_KEY = "mayimunah-application-document-checks-v1";
const STATUSES: Status[] = ["Not started", "Preparing", "Ready", "Submitted", "Interview", "Closed"];
const DOCS = ["Academic CV", "BSc and Honours certificates and transcripts", "Current MSc transcript and enrolment proof", "MSc completion timeline / official completion letter", "Research statement or motivation letter", "Publication list and research links", "English-medium instruction evidence", "Referees who agreed to support applications"];
const LEGACY_MASTER = ["Academic CV tailored for PhD applications","BSc degree certificate","BSc full transcript","Current MSc transcript","MSc registration/enrolment proof","Official expected-completion or completion letter from UWC","One-page MSc thesis summary","Publication list with DOI and links","Google Scholar and ORCID links","GitHub profile with presentable research/code projects","Two or three referees who have agreed to be contacted","Master motivation-letter building blocks","Master research statement","Degree grading-scale explanation","Passport scan for later immigration/admin stages"];
const MASTER = [...LEGACY_MASTER, "Honours certificate and transcript", "Official English-medium instruction letter"];
const freshProgress = (): Progress => ({ status: "Not started", notes: "", actionDate: "", checked: {} });
const freshSaved = (): Saved => ({ version: 2, progress: {}, custom: [], archive: [], master: {}, rates: {EUR:18.63, CHF:19.76, CAD:11.56, AUD:11.50, NZD:9.36, SEK:1.68}, rateDate: "2026-09-02" });
const common = { timing: "Ideal target" as const, mscBy: "Needs confirmation", msc: "Apply with current records. Confirm the qualifying degree and completion evidence required before enrolment.", maths: "Depends on supervisor", documents: DOCS, references: "Confirm the number of referees and letter deadline in the application instructions.", english: "Prepare UWC English-medium evidence; any test waiver needs confirmation.", verified: "Shortlist information; confirm remaining requirements on the official page.", deadlineNote: "Closing time/time zone not confirmed; submit early." };
const make = (o: Pick<Opportunity,"id"|"title"|"institution"|"country"|"deadline"|"start"|"funding"|"official"|"fit"|"action"> & Partial<Opportunity>): Opportunity => ({...common,...o});
const opportunities: Opportunity[] = [
  make({id:"eth-ai-2027",title:"AI Center Doctoral Fellowship",institution:"ETH Zurich",country:"Switzerland",deadline:"2026-10-27",deadlineNote:"27 October, 16:00 CET",start:"Usually September 2027; other dates by agreement",funding:"100% doctoral salary: CHF 73,100 in year 1; CHF 78,300 / 83,500 in years 2 / 3 (gross).",amount:73100,currency:"CHF",period:"year",official:"https://ai.ethz.ch/research/phd-and-postdoc-programs/phd-fellowships.html",portalNote:"Use the fellowship page for its current online application link.",mscBy:"Three months before start",msc:"Master's completed at least three months before the fellowship and no later than June 2027.",fit:"Computer vision, trustworthy AI and multimodal research. Choose an applied project and compatible mentors.",action:"Choose mentors, outline your motivation and plan the short research video.",documents:["CV","Degree certificates and transcripts","Motivation letter (check PDF guidelines for length)","2–5 minute video","Two mandatory recommendation letters; third optional"],references:"Arrange 2–3 letters submitted directly through the system.",verified:"Deadline, salary, MSc rule and document types checked 15 September 2026. Portal URL not exposed in retrieved page."}),
  make({id:"imprs-is-2027",title:"Intelligent Systems PhD",institution:"IMPRS-IS",country:"Germany",deadline:"2026-11-15",deadlineNote:"15 November, end of day Anywhere on Earth (AoE)",start:"February 2027 or later; request May–September",timing:"Needs confirmation",funding:"Reported minimum 65% TVöD E13. Your 75% / 100% contract preference is NOT yet confirmed.",official:"https://imprs.is.mpg.de/application",portalNote:"Portal expected in September; follow the official application page.",fit:"Vision, multimodal AI and machine learning; select applied groups.",action:"Confirm a 75% or 100% contract, start flexibility and three referees before committing.",msc:"Completed or soon-expected Master's accepted for application. Confirm completion-letter acceptance for your agreed start.",documents:["CV","Unofficial transcripts from all university studies","Two-page motivation letter","Three referee contacts and their letters","English proficiency evidence","Optional thesis, publications or portfolio"],references:"Three letters must reach the system by the application deadline.",english:"Other evidence can include English study/work or a thesis/paper in English.",verified:"Application deadline, start window and checklist checked 15 September 2026; contract percentage still to confirm."}),
  make({id:"ellis-2027",title:"ELLIS PhD Programme",institution:"ELLIS network",country:"Europe",deadline:"2026-10-31",opens:"2026-10-01",deadlineNote:"31 October, 23:59 AoE; referee letters by 25 November AoE",start:"2027, agreed with the recruiting institution",timing:"Needs confirmation",funding:"Funding and employment conditions depend on the recruiting advisor and host.",official:"https://ellis.eu/news/ellis-phd-program-call-for-applications-2026",portalNote:"Portal link is scheduled to appear on 1 October. Check host applications in parallel.",fit:"Broad AI, vision and NLP options; shortlist empirical research groups.",action:"Prepare the two-page letter and arrange references before the portal opens.",documents:["Two-page motivation letter including research statement","CV","BSc/MSc transcripts and English translations","Contact details of 2–3 consenting referees","Optional research portfolio PDF under 20 MB"],references:"Request letters through the portal BEFORE 31 October; letters due 25 November. Do not wait for shortlisting.",verified:"2027 call, opening date, deadline and checklist checked 15 September 2026."}),
  make({id:"bmai-2027",title:"Biomedical Artificial Intelligence PhD",institution:"Max Planck School of Biomedical AI",country:"Germany",deadline:"2026-12-01",deadlineNote:"Application 1 December; recommendations 10 December",start:"September 2027",funding:"E13 employment reported; confirm salary percentage and exact contract.",official:"https://biomedicalai.maxplanckschools.org/4056/application-process",portal:"https://mps.cloud.opencampus.net/user/register",portalNote:"Official portal link confirmed; automated access returned 403. Open it in your browser.",fit:"Applied vision and multimodal biomedical data; assess the biology and maths expected by each group.",action:"Choose up to three fellows and request letters early.",msc:"Current Master's enrolment proof and transcript accepted at application.",documents:["BSc certificate and transcript","MSc certificate OR enrolment proof and transcript","Passport or ID copy","Academic CV","Motivation letter","Up to three proposed supervisors","Two referee contacts","English proficiency evidence"],references:"Two recommendations, due 10 December.",verified:"Start, deadline, portal link and checklist checked 15 September 2026."}),
  make({id:"cs-max-planck-2027",title:"Computer and Information Science Doctorate",institution:"CS@Max Planck",country:"Germany",deadline:"2026-12-15",start:"Fall 2027",funding:"Full support reported; confirm employment percentage, salary and benefits.",official:"https://www.cis.mpg.de/csmax-planck-admissions/",portal:"https://apply.cis.mpg.de/register/csmaxplanckdoctorate",mscBy:"Qualifying degree at application",msc:"A Bachelor's OR Master's is accepted. Your unfinished MSc is not the sole qualifying route.",fit:"Broad CS programme with vision, AI and systems options.",action:"Build a focused statement of purpose and choose research areas.",documents:["CV","Transcripts","Statement of purpose","At least two referee contacts","English scores unless exempt","GRE encouraged, not listed as mandatory"],references:"Letters requested after the first review, rather than automatically.",english:"Significant prior education in English can meet the exemption rule.",verified:"Recurring December deadline, portal and checklist checked 15 September 2026."}),
  make({id:"ubc-cs-2027",title:"Computer Science PhD",institution:"University of British Columbia",country:"Canada",deadline:"2026-12-15",start:"September 2027; January 2028 alternative",funding:"2026–27 package reported as CAD 46,236/year, before tuition/fees; confirm 2027 offer.",amount:46236,currency:"CAD",period:"year",official:"https://www.cs.ubc.ca/students/grad/admissions",portal:"https://www.grad.ubc.ca/prospective-students/application-admission/apply-online",portalNote:"Official application gateway; choose Computer Science PhD.",fit:"Vision, ML and applied CS; identify suitable supervisors.",action:"Read department requirements and prepare supervisor preferences.",verified:"2027/28 intake dates and 15 December deadline checked 15 September 2026. Checklist below is a preparation list pending portal review."}),
  make({id:"ista-2027",title:"PhD Programme — Computer Science",institution:"ISTA",country:"Austria",deadline:"2027-01-08",opens:"2026-10-26",deadlineNote:"8 January, 15:00 CET; letters by 12 January, 23:59 CET",start:"September 2027; shortlist reports 15 September",funding:"Salaried doctorate; confirm current pay and contract.",official:"https://phd.ista.ac.at/phd-application-admission/",portalNote:"Opens late October; 26 October is a planning reminder, not an announced opening day.",fit:"Rotations provide choice; inspect CS groups for applied work.",action:"Research rotation groups; revisit portal in late October.",references:"Referee details due 8 January; letters due 12 January.",verified:"2027 deadline and late-October opening checked 15 September 2026. Exact start and checklist need confirmation."}),
  make({id:"mpi-sws-2027",title:"Doctoral Programme",institution:"MPI for Software Systems",country:"Germany",deadline:"2026-12-31",deadlineNote:"Planned December review round; rolling applications",start:"Flexible in 2027, subject to advisor agreement",timing:"Needs confirmation",funding:"Fully funded route reported; confirm a 75% / 100% employment contract.",official:"https://www.mpi-sws.org/graduate-studies/",fit:"Choose applied AI systems or trustworthy ML; some groups focus on theory.",action:"Identify an applied group and confirm research and employment terms."}),
  make({id:"imprs-trust-2027",title:"Trustworthy Computing PhD",institution:"IMPRS-TRUST",country:"Germany",deadline:"2026-12-15",deadlineNote:"Planned December review round; rolling applications",start:"2027; exact start to confirm",timing:"Needs confirmation",funding:"Full funding reported; contract percentage and amount need confirmation.",official:"https://www.imprs-trust.mpg.de/phd-application/",fit:"Secure ML and trustworthy AI may fit; avoid proof-heavy theory projects.",action:"Find a suitable ML supervisor and check the degree route."}),
  make({id:"anu-2027",title:"CS PhD + RTP / University Scholarship",institution:"Australian National University",country:"Australia",deadline:"2027-04-15",deadlineNote:"Reported Round 2 deadline; not independently confirmed",start:"Target mid/late 2027; scholarship start limit to confirm",timing:"Needs confirmation",funding:"Reported AUD 40,475/year stipend; separate tuition and health-cover award conditions to confirm.",amount:40475,currency:"AUD",period:"year",official:"https://www.anu.edu.au/study/scholarships",fit:"Supervisor-led applied CS/AI project; admission and scholarship are separate decisions.",action:"Find a supervisor and verify the international scholarship round before applying."}),
  make({id:"delft-waltz-2027",title:"Decentralized & Trustworthy AI Pipelines (WALTZ)",institution:"TU Delft",country:"Netherlands",deadline:"2026-09-24",start:"Not stated; request a start after MSc completion",timing:"Needs confirmation",funding:"€3,204–€4,051 gross/month over four years; holiday and year-end allowances extra.",amount:3204,currency:"EUR",period:"month",official:"https://careers.tudelft.nl/job/Delft-PhD-Position-Decentralized-and-Trustworthy-AI-Pipelines-(EU-project-WALTZ)-2628-CD/1370001157/",portalNote:"Use Apply now on the advert; the direct application URL redirected during checking.",msc:"MSc completed or close to completion accepted at application; confirm a 2027 start.",maths:"Moderate / confirm",fit:"Reproducible evaluation, Python, HPC and trustworthy AI. Distributed learning and privacy are new areas to develop.",action:"Ask Dr Jérémie Decouchant about a 2027 start and the balance of empirical work versus theory.",verified:"Advert, funding and pending-MSc wording checked 15 September 2026. Confirm the complete upload checklist."}),
  make({id:"kth-urban-2027",title:"Urban Heat Prediction with AI & Earth Observation",institution:"KTH",country:"Sweden",deadline:"2026-09-24",deadlineNote:"24 September, midnight CEST",start:"By agreement; request May 2027 onward",timing:"Needs confirmation",funding:"100% employment; salary follows KTH doctoral agreement. Exact amount not confirmed.",official:"https://www.kth.se/lediga-jobb/964277?l=en",portalNote:"Use Apply here on the official vacancy (PA-2026-2917).",mscBy:"Eligibility before admission",msc:"Master's OR specified second-cycle credits/equivalent; ask KTH to assess your qualifications.",maths:"Moderate / confirm",fit:"Vision, multimodal Earth observation and generative models. Diffusion modelling may involve substantial maths: discuss the project first.",action:"Confirm start flexibility and mathematical expectations with the supervisor.",documents:["Certified diplomas and grades; translations where needed","Language-requirement evidence","CV","Application letter (maximum two pages)","Representative publications/reports, or abstracts and links"],verified:"Deadline, agreed start, employment and checklist checked 15 September 2026."}),
  make({id:"epfl-edic-2027",title:"EDIC Computer & Communication Sciences PhD",institution:"EPFL",country:"Switzerland",deadline:"2026-12-01",deadlineNote:"1 December, 23:59 CET; submit early for referee letters",start:"September 2027",funding:"All admitted students financially supported; exact salary to confirm.",official:"https://www.epfl.ch/education/phd/edic-computer-and-communication-sciences/edic-computer-and-communication-sciences/edic-how-to-apply/",portal:"https://isa.epfl.ch/imoniteur_ISAP/!formInscrs.connection?ww_c_formulaire=EDOC_FORMV3",mscBy:"Start date / qualifying degree",msc:"Qualifying four/five-year Bachelor's or Master's needed at enrolment. Current diplomas or expected-completion attestation accepted for application.",fit:"Broad CS, vision and ML. Identify applied labs in the statement.",action:"Draft the 1–2 page statement and arrange three recommendations.",documents:["Transcripts including grading scales","Available diplomas or expected-completion attestation","CV in English","Statement of purpose (1–2 pages)","Three recommendation letters","Passport or official ID","English test/evidence: confirm waiver"],references:"Three letters; submission triggers referee invitations. Allow time before 1 December.",english:"Published wording uses 'or' between native-speaker and English-degree conditions; confirm exemption instead of assuming it.",verified:"Deadline, portal, qualifying degree and checklist checked 15 September 2026."}),
  make({id:"cispa-2027",title:"Trustworthy ML / Data Science PhD",institution:"CISPA",country:"Germany",deadline:"",start:"Negotiated with research group",timing:"Needs confirmation",funding:"Full-time TVöD, up to E13; advertised starting salary around €4,000 gross/month.",amount:4000,currency:"EUR",period:"month",official:"https://career.cispa.de/phd",portalNote:"General call closed. Follow current group-specific job adverts.",fit:"Target empirical trustworthy ML, not mathematical cryptography or formal-methods projects.",action:"Watch group vacancies and approach an appropriate ML supervisor.",verified:"General-call closure and advertised funding checked 15 September 2026. Group-specific requirements vary."}),
  make({id:"waterloo-cs-2027",title:"Computer Science PhD",institution:"University of Waterloo",country:"Canada",deadline:"2026-10-01",deadlineNote:"Shortlist: 1 October for May; 1 December for September. Reconfirm intake deadlines.",start:"Target May or September 2027",funding:"Reported international package CAD 51,090/year; confirm fees, conditions and 2027 funding.",amount:51090,currency:"CAD",period:"year",official:"https://uwaterloo.ca/future-graduate-students/programs/by-faculty/math/computer-science-doctor-philosophy-phd",fit:"Computer Science degree; being in the Faculty of Mathematics does not itself make this a Mathematics PhD. Select applied AI supervisors.",action:"Check the May-intake deadline and whether MSc award timing permits enrolment.",mscBy:"Start date",msc:"Normal PhD-M route needs an MSc; confirm documentation and timing for May enrolment."}),
  make({id:"toronto-cs-2027",title:"Computer Science PhD",institution:"University of Toronto",country:"Canada",deadline:"",opens:"2026-10-01",start:"Fall 2027",funding:"Reported CAD 39,500 living allowance after tuition/incidentals; verify current package and tax treatment.",amount:39500,currency:"CAD",period:"year",official:"https://web.cs.toronto.edu/graduate/how-to-apply",portalNote:"Opens in October; 1 October is a planning reminder. Exact deadline not yet confirmed.",fit:"Applied ML, vision and NLP through supervisor matching.",action:"Choose faculty and arrange three referees, then check the October call.",references:"Three referees; confirm letter submission deadline.",verified:"October 2026 opening for Fall 2027 checked 15 September 2026. Funding and final checklist need confirmation."}),
  make({id:"sydney-2027",title:"CS PhD + RTP / USYDIS Scholarship",institution:"University of Sydney",country:"Australia",deadline:"2026-12-18",start:"Research periods 3/4 of 2027; target July or later",funding:"Reported 2027 stipend AUD 44,293/year; scholarship tuition/health-cover terms to verify.",amount:44293,currency:"AUD",period:"year",official:"https://www.sydney.edu.au/scholarships/australian-government-research-training-program/rtp-international.html",fit:"Supervisor-led applied AI/vision proposal; competitive scholarship selection.",action:"Secure supervisor support and prepare the research proposal and research-experience evidence.",verified:"18 December deadline for 2027 periods 3/4 checked 15 September 2026. Other fields need final confirmation."}),
  make({id:"stanford-cs-2027",title:"Computer Science PhD",institution:"Stanford University",country:"United States",deadline:"2026-12-08",start:"Autumn 2027",funding:"PhD support reported subject to satisfactory progress; exact package to confirm.",official:"https://www.cs.stanford.edu/admissions-graduate-application-deadlines",fit:"Ambitious reach application in vision or multimodal AI; select empirical labs.",action:"Review CS requirements, faculty and application costs before tailoring a statement.",mscBy:"Qualifying Bachelor's before start",msc:"Master's is not the required entry qualification; confirm Bachelor's equivalence.",verified:"8 December 2026 deadline for Autumn intake checked 15 September 2026. Checklist below is preparatory."}),
  make({id:"mcgill-cs-2027",title:"Computer Science PhD",institution:"McGill University",country:"Canada",deadline:"2026-12-15",start:"Fall 2027",funding:"Funding package depends on offer. Earlier shortlist quoted CAD 25,000/year average; not treated as a guaranteed offer.",official:"https://www.cs.mcgill.ca/academic/graduate/applying/",fit:"Vision, NLP and applied AI supervisor options.",action:"Identify supervisors and check the funding remaining after fees.",mscBy:"Official degree award",msc:"Shortlist states MSc award required by registration. Confirm with admissions.",verified:"Recurring international 15 December deadline checked 15 September 2026."}),
  make({id:"waikato-2027",title:"CS PhD + Doctoral Scholarship",institution:"University of Waikato",country:"New Zealand",deadline:"",start:"Flexible 2027 after admission and funding",timing:"Needs confirmation",funding:"Reported up to NZD 33,000/year plus tuition/student-services support; confirm current conditions.",amount:33000,currency:"NZD",period:"year",official:"https://www.waikato.ac.nz/study/scholarships/find-a-scholarship/university-of-waikato-doctoral-scholarship/",fit:"Supervisor-led applied CS research; scholarship is competitive.",action:"Start supervisor discussions; confirm completed-degree and invitation requirements before formal submission.",mscBy:"Application — confirm",msc:"Shortlist says qualifying research degree must be completed before formal application; supervisor outreach can begin sooner."})
];

const confirmedDetails: Record<string, Partial<Opportunity>> = {
  "delft-waltz-2027": { documents:["Cover letter (maximum one page)","CV including publications where applicable","BSc and MSc transcripts","MSc thesis if applicable","English-language proof if applicable","Optional code repository links"], verified:"Advert, funding, pending-MSc wording and checklist checked 15 September 2026. Start date remains unconfirmed." },
  "imprs-trust-2027": { mscBy:"Qualifying Bachelor's or Master's", msc:"Applicants may hold or be about to receive a Bachelor's or Master's; certificates are uploaded if already received.", documents:["CV","Statement of purpose naming preferred supervisor/group","Available Bachelor's / Master's certificates","Academic transcripts and grading scheme","Two referee contacts using institutional email addresses","English scores optional but encouraged","GRE optional"], references:"Two academic contacts using institutional addresses; preferably include your thesis supervisor.", verified:"Recurring review deadlines, qualifying-degree wording and documents checked 15 September 2026." }
};
for (const o of opportunities) Object.assign(o, confirmedDetails[o.id] || {});

function safeUrl(value: unknown): string | undefined { if(typeof value !== "string") return; try { const u = new URL(value); return u.protocol === "https:" || u.protocol === "http:" ? u.href : undefined; } catch { return; } }
function dateKey(d = new Date()): string { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function dayOffset(date: string, today: string): number { return (Date.parse(date+"T12:00:00Z")-Date.parse(today+"T12:00:00Z"))/86400000; }
function record(x: unknown): x is Record<string, unknown> { return !!x && typeof x === "object" && !Array.isArray(x); }
function normalizeProgress(value: unknown): Progress { const p = record(value) ? value : {}; return { status: STATUSES.includes(p.status as Status) ? p.status as Status : "Not started", notes: typeof p.notes === "string" ? p.notes : "", actionDate: typeof p.actionDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(p.actionDate) ? p.actionDate : "", checked: record(p.checked) ? Object.fromEntries(Object.entries(p.checked).filter(([,v])=>typeof v === "boolean")) as Record<string,boolean> : {} }; }
function normalizeSaved(value: unknown): Saved {
  if (!record(value) || value.version !== 2 || !record(value.progress)) throw new Error("This is not a tracker v2 backup.");
  const s = freshSaved();
  s.progress = Object.fromEntries(Object.entries(value.progress).map(([k,v])=>[k,normalizeProgress(v)]));
  s.master = record(value.master) ? Object.fromEntries(Object.entries(value.master).filter(([,v])=>typeof v === "boolean")) as Record<string,boolean> : {};
  s.archive = Array.isArray(value.archive) ? value.archive.filter(record) : [];
  s.custom = Array.isArray(value.custom) ? value.custom.filter(record).filter(o=>typeof o.id === "string" && o.id.startsWith("custom-") && typeof o.title === "string" && typeof o.institution === "string").map(o=>make({id:String(o.id),title:String(o.title),institution:String(o.institution),country:String(o.country||"To confirm"),deadline:typeof o.deadline === "string" && /^\d{4}-\d{2}-\d{2}$/.test(o.deadline)?o.deadline:"",start:String(o.start||"To confirm"),funding:String(o.funding||"To confirm"),official:safeUrl(o.official)||"",fit:String(o.fit||"Not assessed"),action:String(o.action||"Verify requirements"),custom:true,timing:"Needs confirmation"})) : [];
  if(Array.isArray(value.custom)) for(const o of s.custom) {
    const original=value.custom.find(x=>record(x)&&x.id===o.id);
    if(record(original) && Array.isArray(original.documents)) o.documents=original.documents.filter((x):x is string=>typeof x === "string");
  }
  if(record(value.rates)) for(const key of Object.keys(s.rates)) { const n = value.rates[key]; if(typeof n === "number" && Number.isFinite(n) && n>0) s.rates[key]=n; }
  if(typeof value.rateDate === "string") s.rateDate=value.rateDate;
  return s;
}
function migrateLegacy(rows: unknown, checks: unknown): Saved {
  if(!Array.isArray(rows)) throw new Error("Old opportunities must be an array.");
  const s=freshSaved(); const c=record(checks)?checks:{};
  for(const row of rows.filter(record)) {
    const id=String(row.id||"");
    if(row.custom === true || id.startsWith("custom-")) {
      const o=make({id:id.startsWith("custom-")?id:`custom-${id}`,title:String(row.title||"Saved opportunity"),institution:String(row.institution||"To confirm"),country:String(row.country||"To confirm"),deadline:typeof row.deadline === "string"?row.deadline.slice(0,10):"",start:String(row.start||"To confirm"),funding:String(row.funding||"To confirm"),official:safeUrl(row.officialUrl)||safeUrl(row.applyUrl)||"",fit:String(row.whyFit||"Not assessed"),action:String(row.action||"Verify requirements"),documents:Array.isArray(row.documents)?row.documents.filter((x):x is string=>typeof x === "string"):DOCS,custom:true,timing:"Needs confirmation"});
      s.custom.push(o); s.progress[o.id]={...normalizeProgress(row),checked:Object.fromEntries(o.documents.map((d,i)=>[d,c[`${id}-${i}`]===true]))};
    } else s.archive.push({...row,documentChecks:Object.fromEntries(Object.entries(c).filter(([key])=>key.startsWith(id+"-")))});
  }
  LEGACY_MASTER.forEach((label,i)=>{s.master[label]=c[`master-${i}`]===true;}); return s;
}
function download(name: string, content: string, type: string) { const url=URL.createObjectURL(new Blob([content],{type})); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }

export default function Home() {
  const [saved,setSaved]=useState<Saved>(freshSaved); const [ready,setReady]=useState(false); const [error,setError]=useState("");
  const [today,setToday]=useState(""); const [tab,setTab]=useState("All applications"); const [query,setQuery]=useState("");
  const [country,setCountry]=useState("All countries"); const [timing,setTiming]=useState("All starts"); const [statusFilter,setStatusFilter]=useState("All statuses");
  const [adding,setAdding]=useState(false); const [draft,setDraft]=useState({title:"",institution:"",country:"",deadline:"",official:""});
  useEffect(()=>{setToday(dateKey()); const tick=setInterval(()=>setToday(dateKey()),60000); try { const raw=localStorage.getItem(KEY); if(raw) setSaved(normalizeSaved(JSON.parse(raw))); else {const legacy=localStorage.getItem(OLD_KEY); if(legacy) setSaved(migrateLegacy(JSON.parse(legacy),JSON.parse(localStorage.getItem(OLD_CHECK_KEY)||"{}")));} setReady(true); } catch {setError("Saved data could not be read. It has not been overwritten. Export the raw backup below before restoring a valid backup.");} return()=>clearInterval(tick);},[]);
  useEffect(()=>{if(ready) try {localStorage.setItem(KEY,JSON.stringify(saved));} catch {setError("Browser storage is unavailable or full. Export a backup to keep your latest changes.");}},[saved,ready]);
  const all=[...opportunities,...saved.custom];
  const progress=(id:string)=>saved.progress[id]||freshProgress();
  const update=(id:string,patch:Partial<Progress>)=>setSaved(s=>({...s,progress:{...s.progress,[id]:{...(s.progress[id]||freshProgress()),...patch}}}));
  const finished=(o:Opportunity)=>["Submitted","Interview","Closed"].includes(progress(o.id).status);
  const weekStart=today ? (new Date(today+"T12:00:00").getDay()+6)%7 : 0;
  const inWeek=(d:string,next=false)=>!!d && !!today && dayOffset(d,today)>= (next?7-weekStart:-weekStart) && dayOffset(d,today)<(next?14-weekStart:7-weekStart);
  const matches=(o:Opportunity)=>{
    const p=progress(o.id); const search=`${o.title} ${o.institution} ${o.country} ${o.fit}`.toLowerCase();
    if(!search.includes(query.toLowerCase()) || country!=="All countries"&&o.country!==country || timing!=="All starts"&&o.timing!==timing || statusFilter!=="All statuses"&&p.status!==statusFilter) return false;
    if(tab==="This week" || tab==="Next week") return !finished(o) && (inWeek(p.actionDate,tab==="Next week") || inWeek(o.deadline,tab==="Next week"));
    if(tab==="Opening / watch") return !finished(o) && (!o.deadline || !!o.opens&&o.opens>today);
    return true;
  };
  const shown=all.filter(matches).sort((a,b)=>(a.deadline||"9999").localeCompare(b.deadline||"9999"));
  const money=(o:Opportunity)=>o.amount&&o.currency&&saved.rates[o.currency]?`≈ ${new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(o.amount*saved.rates[o.currency])} / ${o.period} · planning estimate`:"Rand estimate needs a confirmed amount";
  const exportBackup=()=>download("mayimunah-phd-backup.json",JSON.stringify(saved,null,2),"application/json");
  async function restore(file?:File) {if(!file)return; try {const parsed=JSON.parse(await file.text()); const next=record(parsed)&&parsed.version===2?normalizeSaved(parsed):record(parsed)?migrateLegacy(parsed.opportunities,parsed.checks):null;if(!next)throw new Error(); if(ready)exportBackup(); setSaved(next);setReady(true);setError("");}catch{setError("That backup could not be restored. Your existing data was kept.");}}
  const exportCsv=()=>{const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`; const rows=all.map(o=>[o.institution,o.title,o.country,o.deadline,o.deadlineNote,o.start,o.timing,o.mscBy,o.funding,money(o),o.maths,o.official,o.portal||"",progress(o.id).status,progress(o.id).actionDate,progress(o.id).notes,o.documents.join("; ")]);download("mayimunah-phd-applications.csv",[["Institution","PhD","Country","Deadline","Deadline note","Start","Timing","MSc required by","Funding","ZAR estimate","Maths assessment","Official page","Portal","Status","Action date","Notes","Documents"],...rows].map(r=>r.map(cell).join(",")).join("\r\n"),"text/csv");};
  return <main className="phd-app"><div className="phd-shell">
    <header className="phd-header"><div><p className="phd-eyebrow">Your next chapter</p><h1>Mayimunah&apos;s PHD Applications tracker</h1><p>Applied AI, computer vision and multimodal research. Plan your applications around a start from February 2027 onward.</p></div><div className="phd-actions"><button onClick={exportCsv}>Export CSV</button><button onClick={exportBackup} disabled={!ready}>Backup</button><label className="phd-button">Restore backup<input className="phd-file" type="file" accept=".json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value="";}}/></label><button className="phd-primary" disabled={!ready} onClick={()=>setAdding(!adding)}>+ Add application</button></div></header>
    {error&&<div role="alert" className="phd-notice">{error} <button onClick={()=>{try{download("tracker-raw-recovery.json",JSON.stringify({v2:localStorage.getItem(KEY),v1:localStorage.getItem(OLD_KEY),checks:localStorage.getItem(OLD_CHECK_KEY)}),"application/json");}catch{setError("Browser storage cannot be accessed. Your files have not been changed.");}}}>Export raw saved data</button></div>}
    <section className="phd-intro"><div><p className="phd-eyebrow">Your starting window</p><h2>Prepare now. Start when you’re ready.</h2><p>Target May–September 2027. February–April needs confirmation that your MSc completion evidence is accepted before employment or enrolment.</p></div><div><p className="phd-eyebrow">Your research direction</p><p>Prioritise applied CS and AI. Exclude mathematics PhDs and proof-heavy projects. For broad programmes, assess the supervisor and proposed project before committing.</p><p>Germany: confirm a 75% or 100% contract. “Fully funded” alone does not establish the percentage.</p></div></section>
    {adding&&<form className="phd-card phd-add" onSubmit={e=>{e.preventDefault();if(!draft.title.trim()||!draft.institution.trim())return;const url=safeUrl(draft.official);if(draft.official&&!url){setError("Please enter a valid http or https official URL.");return;}const id=`custom-${Date.now()}`;setSaved(s=>({...s,custom:[...s.custom,make({...draft,id,official:url||"",start:"To confirm",funding:"To confirm",fit:"Not assessed",action:"Check funding, deadline and eligibility",custom:true,timing:"Needs confirmation"})]}));setDraft({title:"",institution:"",country:"",deadline:"",official:""});setAdding(false);}}><h2>Add an application</h2>{(["title","institution","country","deadline","official"] as const).map(k=><label key={k}>{k==="official"?"Official URL":k}<input required={k==="title"||k==="institution"} type={k==="deadline"?"date":k==="official"?"url":"text"} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<button className="phd-primary">Save application</button></form>}
    <nav className="phd-tabs" aria-label="Application views">{["All applications","This week","Next week","Opening / watch","Documents","Archive"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
    {tab!=="Documents"&&tab!=="Archive"&&<><div className="phd-filters"><label>Search<input placeholder="University, country or research topic" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Country<select value={country} onChange={e=>setCountry(e.target.value)}>{["All countries",...Array.from(new Set(all.map(o=>o.country))).sort()].map(v=><option key={v}>{v}</option>)}</select></label><label>Start feasibility<select value={timing} onChange={e=>setTiming(e.target.value)}>{["All starts","Ideal target","Needs confirmation"].map(v=><option key={v}>{v}</option>)}</select></label><label>Progress<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}>{["All statuses",...STATUSES].map(v=><option key={v}>{v}</option>)}</select></label></div>
    <p className="phd-caption">Week views use your device’s current week, application deadlines and your chosen next-action dates. Start feasibility is a planning assessment, not an admission decision.</p>
    <div className="phd-list">{shown.map(o=>{const p=progress(o.id);const closed=!!today&&!!o.deadline&&o.deadline<today;return <article className="phd-card" key={o.id}><div className="phd-card-top"><div><div className="phd-tags"><span>{o.country}</span><span className={o.timing==="Ideal target"?"phd-good":"phd-check"}>{o.timing}</span>{closed&&<span className="phd-check">Deadline passed</span>}{o.opens&&o.opens>today&&<span>Opening later</span>}</div><p className="phd-institution">{o.institution}</p><h2>{o.title}</h2></div><label>Application status<select disabled={!ready} value={p.status} onChange={e=>update(o.id,{status:e.target.value as Status})}>{STATUSES.map(v=><option key={v}>{v}</option>)}</select></label></div><div className="phd-facts"><div><h3>Apply by</h3><p>{o.deadline||"Rolling / to confirm"}</p><small>{o.deadlineNote}</small></div><div><h3>Possible start</h3><p>{o.start}</p></div><div><h3>MSc required by</h3><p>{o.mscBy}</p></div><div><h3>Funding</h3><p>{o.funding}</p><small className="phd-rand">{money(o)}</small></div></div><p className="phd-next"><strong>Next step:</strong> {o.action}</p><div className="phd-actions">{safeUrl(o.official)&&<a className="phd-button" href={safeUrl(o.official)} target="_blank" rel="noreferrer">Official details ↗</a>}{safeUrl(o.portal)&&<a className="phd-button phd-primary" href={safeUrl(o.portal)} target="_blank" rel="noreferrer">Application route ↗</a>}</div>{o.portalNote&&<p className="phd-caption">{o.portalNote}</p>}<details className="phd-detail"><summary>Documents, eligibility & notes</summary><div className="phd-detail-grid"><div><h3>Research fit</h3><p>{o.fit}</p><h3>Maths intensity · assessment</h3><p>{o.maths}</p><h3>MSc timing</h3><p>{o.msc}</p><h3>References</h3><p>{o.references}</p><h3>English evidence</h3><p>{o.english}</p></div><div><h3>{o.documents===DOCS?"Preparation checklist · confirm portal requirements":"Application document checklist"}</h3>{o.documents.map(d=><label className="phd-checklist" key={d}><input type="checkbox" disabled={!ready} checked={!!p.checked[d]} onChange={e=>update(o.id,{checked:{...p.checked,[d]:e.target.checked}})}/><span>{d}</span></label>)}<label className="phd-field">Next-action date<input type="date" disabled={!ready} value={p.actionDate} onChange={e=>update(o.id,{actionDate:e.target.value})}/></label><label className="phd-field">Private notes<textarea disabled={!ready} value={p.notes} onChange={e=>update(o.id,{notes:e.target.value})} placeholder="Supervisor shortlist, questions, draft progress…"/></label></div></div><p className="phd-caption">{o.verified}</p></details></article>;})}{!shown.length&&<p className="phd-empty">No applications match this view. Set a next-action date under an application’s notes to schedule preparation for this week or next week.</p>}</div></>}
    {tab==="Documents"&&<section className="phd-card"><p className="phd-eyebrow">Reusable application materials</p><h2>Your document checklist</h2><p>Use current records and state your actual expected MSc completion date. The April 2027 ceremony does not establish when all degree requirements will be met.</p><div className="phd-master">{MASTER.map(d=><label key={d} className="phd-checklist"><input type="checkbox" disabled={!ready} checked={!!saved.master[d]} onChange={e=>setSaved(s=>({...s,master:{...s.master,[d]:e.target.checked}}))}/>{d}</label>)}</div></section>}
    {tab==="Archive"&&<section className="phd-card"><h2>Previous shortlist</h2><p>Old built-in opportunities are kept here with their saved notes and status. They are excluded from the active application plan.</p>{!saved.archive.length&&<p>No previous entries were found in this browser.</p>}{saved.archive.map((o,i)=><details className="phd-detail" key={String(o.id||i)}><summary>{String(o.institution||"")} — {String(o.title||"Previous application")}</summary><p>Status: {String(o.status||"Not started")}</p><p>{String(o.notes||"No saved notes")}</p><pre>{JSON.stringify(o,null,2)}</pre></details>)}</section>}
    <details className="phd-card phd-rates"><summary>Rand conversion settings</summary><p>These are editable planning rates carried over from the previous tracker, dated 2 September 2026. They are not live or independently refreshed. Amounts labelled “reported” still need confirmation; tax, fees and living costs differ.</p><div className="phd-rate-grid">{Object.entries(saved.rates).map(([currency,rate])=><label key={currency}>Rands per 1 {currency}<input disabled={!ready} type="number" min="0.01" step="0.01" value={rate} onChange={e=>{const n=Number(e.target.value);if(n>0&&Number.isFinite(n))setSaved(s=>({...s,rates:{...s.rates,[currency]:n}}));}}/></label>)}<label>Rate date<input type="date" disabled={!ready} value={saved.rateDate} onChange={e=>setSaved(s=>({...s,rateDate:e.target.value}))}/></label></div><p>Conversion date shown in your backup: {saved.rateDate}</p></details>
    <footer className="phd-footer">Saved in this browser on this site address. Export a backup before changing devices or site addresses. No applications are submitted by this tracker.</footer>
  </div></main>;
}
