"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, Check, ChevronDown, ChevronUp, CircleAlert, Clock3, Download, FileCheck2, Filter, Link2, ListChecks, MapPin, Plus, Search, Sparkles, Target } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

type Status = "Not started" | "Preparing" | "Ready" | "Submitted" | "Interview" | "Closed";
type WindowName = "urgent" | "next" | "later";
type Opportunity = { id:string; title:string; institution:string; country:string; deadline:string|null; deadlineLabel:string; window:WindowName; fit:number; funding:string; start:string; msc:string; applyUrl:string; source:string; tags:string[]; whyFit:string; caution:string; action:string; documents:string[]; status:Status; notes?:string; custom?:boolean };

const STORAGE_KEY = "mayimunah-application-tracker-v1";
const CHECK_KEY = "mayimunah-application-document-checks-v1";

const seedOpportunities: Opportunity[] = [
  { id:"ku-leuven-compliance", title:"PhD Position on Automated Compliance Engineering", institution:"KU Leuven", country:"Belgium", deadline:"2026-09-05T23:59:00+02:00", deadlineLabel:"5 Sep 2026 · 23:59 CET", window:"urgent", fit:8.8, funding:"4-year funded PhD", start:"Not stated", msc:"Master’s required; the advert does not explicitly say whether pending completion is accepted.", applyUrl:"https://www.kuleuven.be/personeel/jobsite/jobs/60733458", source:"Official KU Leuven vacancy · ref. BAP-2026-526", tags:["AI/LLMs","Regulation","Compliance","Software engineering"], whyFit:"The closest thematic match to your regulatory-screening work: automated compliance, explainability, verification and interdisciplinary AI. Your gap is formal information-systems architecture, and the doctorate is in Business Economics (Management Informatics), not Computer Science.", caution:"Very short deadline. The motivation must be personal, one paragraph and no more than half a page. Do not submit generic AI-sounding wording.", action:"Apply first. Update the CV with your MSc thesis title, expected completion, final grades where available, and supervisor. Draft the half-page motivation in your own voice.", documents:["CV with MSc programme, country, expected completion, thesis title/year/supervisor and academic achievements","Transcript of grades and prior qualifications","One-paragraph motivation letter (maximum half a page)"], status:"Not started" },
  { id:"leiden-imaging", title:"PhD in Computational Imaging for High-Throughput Applications", institution:"Leiden University", country:"Netherlands", deadline:"2026-09-05T23:59:00+02:00", deadlineLabel:"5 Sep 2026", window:"urgent", fit:7.8, funding:"4 years · €3,204–€4,051 gross/month", start:"Not stated", msc:"Advert asks for an MSc; pending-completion wording is not provided.", applyUrl:"https://careers.universiteitleiden.nl/job/PhD-in-Computational-Imaging-for-High-Throughput-Applications-(1_0-fte)/16832-en_US", source:"Official Leiden University vacancy · requisition 16832", tags:["Computer vision","Machine learning","HPC","3D imaging"], whyFit:"Strong transfer from computer vision, machine learning, Python, scientific writing and HPC. The real gap is imaging physics and X-ray reconstruction, so the letter must show willingness to move from RGB package images into computational imaging.", caution:"The official posting requests only a one-page motivation, CV and two referee contacts. A third-party mirror incorrectly mentioned a three-page research plan; we follow the official listing.", action:"Apply second if your two referees agree today. This is a much lighter document pack than Oulu.", documents:["Motivation letter (1 page)","Full CV with publications and Google Scholar or ORCID link","Names and email addresses of at least two scientists who agreed to be contacted"], status:"Not started" },
  { id:"oulu-multimodal-health", title:"Doctoral Researcher in Multimodal AI and Physiological Sensing", institution:"University of Oulu", country:"Finland", deadline:"2026-09-05T23:59:00+03:00", deadlineLabel:"5 Sep 2026 · 23:59 Finnish time", window:"urgent", fit:8.1, funding:"4 years · approx. €2,500–€3,200 gross/month", start:"As soon as possible after recruitment", msc:"Explicitly says the Master’s must be completed before employment starts.", applyUrl:"https://oulunyliopisto.varbi.com/en/what:job/jobID:948111/type:job/where:51/apply:1", source:"Official University of Oulu vacancy · ref. 2026/452", tags:["Multimodal AI","Computer vision","Digital health","Signals"], whyFit:"Very good method match: multimodal data, computer vision, annotation, evaluation and interdisciplinary health research. Physiological signal processing is the main experience gap.", caution:"This is the heaviest urgent application because it needs a position-specific research plan. Do it only after KU Leuven and Leiden, unless this health direction excites you more.", action:"Stretch application for Saturday. Draft a credible three-page plan focused on multimodal evidence integration, missing/noisy signals, uncertainty and safe decision support.", documents:["Cover letter (maximum 1 page)","CV following Finnish research-integrity guidelines","Research plan (maximum 3 pages plus references, Academy of Finland format)","Diplomas/transcripts later if shortlisted","Referees later if shortlisted"], status:"Not started" },
  { id:"marburg-multimodal", title:"Research Assistant (Doctoral Researcher/PhD)", institution:"University of Marburg", country:"Germany", deadline:"2026-09-13T23:59:00+02:00", deadlineLabel:"13 Sep 2026", window:"next", fit:9.2, funding:"3 years · full-time TV-H E13 employment", start:"As soon as possible", msc:"MSc required. Ask whether an official UWC completion letter can bridge the April ceremony delay.", applyUrl:"https://stellenangebote.uni-marburg.de/jobposting/1b633fa4881784909069593d7874a03afa7fef84", source:"Official University of Marburg vacancy · fb12-0019-wmz-2026", tags:["Multimodal AI","Computer vision","NLP","Video","Trustworthy AI"], whyFit:"Excellent fit across computer vision, multimodal AI, Python, ML frameworks, data annotation, evaluation, publications and interdisciplinary applied research. Disinformation and video are new domains, not disqualifiers.", caution:"Do not claim disinformation expertise. Frame the move from image-based multimodal extraction to robust video understanding honestly.", action:"Main application for next week. Aim to submit by Friday 11 September, not on deadline day.", documents:["Motivation letter","Academic CV","University certificates","University transcripts","Previous-employer references only if available"], status:"Not started" },
  { id:"dtu-visual-dialogue", title:"PhD Scholarship in Computer Vision and Multimodal Human-AI Interaction", institution:"Technical University of Denmark (DTU)", country:"Denmark", deadline:"2026-09-20T23:59:00+02:00", deadlineLabel:"20 Sep 2026 · 23:59 Danish time", window:"next", fit:9.6, funding:"Fully funded 3-year PhD employment", start:"Fall 2026", msc:"Explicitly accepts applications before the Master’s is obtained, but the degree must be completed before starting.", applyUrl:"https://efzu.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/7907", source:"Official DTU recruitment portal · job 7907", tags:["Computer vision","Multimodal AI","Generative AI","Human–AI interaction"], whyFit:"Your strongest scientific match: computer vision, multimodal AI, deep learning, dataset creation, Python, evaluation and publication. The visual-dialogue topic is a credible extension of your VLM work.", caution:"The stated Fall 2026 start may be too early. State your academic-completion timeline clearly and ask whether a later agreed start is possible.", action:"Begin after Marburg is drafted. Submit by Friday 18 September.", documents:["Cover letter","CV","BSc and MSc diploma/materials in English","BSc and MSc grade transcripts","Official description of the grading scale","All materials combined as one PDF"], status:"Not started" },
  { id:"ellis-finland", title:"Doctoral Student Positions in AI and Machine Learning", institution:"ELLIS Institute Finland", country:"Finland", deadline:"2026-09-21T23:59:00+03:00", deadlineLabel:"21 Sep 2026 · 23:59 EEST", window:"next", fit:9.1, funding:"Fully funded · four-year doctoral employment", start:"Flexible and individually agreed", msc:"Explicitly accepts applicants who expect to receive the Master’s shortly; submit a completion plan.", applyUrl:"https://www.ellisinstitute.fi/postdoc-and-phd-recruit-autumn-2026", source:"Official ELLIS Institute Finland autumn 2026 call", tags:["Machine learning","AI","Generative modelling","Human-centred AI","AI for health"], whyFit:"A very strong strategic application: dozens of positions, flexible start, pending MSc accepted, excellent computing and broad supervisor matching. Your publications, applied AI, health/regulation work and HPC experience all help.", caution:"The cover letter must name suitable supervisors. Supervisor selection needs real research, not random name-dropping.", action:"Research 3–5 supervisors next week, choose 2–3, and submit by Saturday 19 September.", documents:["Cover letter (1–2 pages, maximum 2)","CV","Publication list with links, if applicable","MSc and BSc transcripts","Latest degree certificate","Plan of MSc completion because the degree is pending","Contact details for 2–3 senior academic referees"], status:"Not started" },
  { id:"lux-world-models", title:"PhD in Trustworthy World Models for Critical Systems", institution:"University of Luxembourg", country:"Luxembourg", deadline:null, deadlineLabel:"Rolling · apply early", window:"next", fit:9.3, funding:"36-month full-time doctoral contract", start:"Not stated", msc:"Master in Computer Science requested; expected/pending wording is not stated.", applyUrl:"https://academicpositions.com/ad/university-of-luxembourg/2026/phd-in-trustworthy-world-models-for-critical-systems/251518", source:"University of Luxembourg advert mirrored by Academic Positions · UOL08387", tags:["Multimodal ML","Foundation models","Trustworthy AI","Critical systems"], whyFit:"Exceptional conceptual match: multimodal vision plus structured data, trustworthy evaluation, critical applications, software demonstrators and healthcare. It connects naturally to product-level evidence integration and conservative regulatory screening.", caution:"No fixed deadline is published and applications are processed on receipt. Verify that the university application portal opens before finalising.", action:"Treat as urgent rolling. Prepare the CV and cover letter after the 5 September applications; aim to submit during 7–11 September.", documents:["Curriculum Vitae","Cover letter aligned to trustworthy multimodal world models","B2 proof in thesis language may be required for doctoral admission"], status:"Not started" },
  { id:"lux-ai-systems", title:"Doctoral Researcher in AI Systems", institution:"University of Luxembourg", country:"Luxembourg", deadline:null, deadlineLabel:"Rolling · apply early", window:"later", fit:8.0, funding:"36 months · €44,531 gross/year", start:"Not stated", msc:"MSc or equivalent requested; CV may give an expected graduation date.", applyUrl:"https://academicpositions.com/ad/university-of-luxembourg/2026/doctoral-researcher-in-ai-systems/252087", source:"University of Luxembourg advert mirrored by Academic Positions · UOL08435", tags:["LLM agents","Trustworthy AI","AI governance","Regulated systems"], whyFit:"Good match to evaluation, rule/VLM interaction, explainability, regulation and building safe decision-support systems. It is less connected to your strongest computer-vision identity and asks for Python plus C/C++.", caution:"Keep this below the multimodal world-model role. Do not overstate agentic-AI or C++ experience.", action:"Apply only after the higher-fit September deadlines are secure.", documents:["CV with degrees/current enrolment and expected date","Thesis title and short summary","Publication list","GitHub link if available","Position-specific cover letter","All university transcripts","B2 proof in thesis language may be required for doctoral admission"], status:"Not started" },
  { id:"bern-self-supervised", title:"PhD in Self-Supervised and Meta-Learning for Rapid Adaptation", institution:"University of Bern", country:"Switzerland", deadline:"2026-10-01T23:59:00+02:00", deadlineLabel:"1 Oct 2026 · 23:59 Zurich time", window:"later", fit:8.3, funding:"Fully funded for four years", start:"1 Oct 2026 or by agreement", msc:"Master’s completed or expected by the agreed starting date.", applyUrl:"https://cvg.unibe.ch/vacancies/project-2/phd/", source:"Official University of Bern Computer Vision Group portal", tags:["Deep learning","Computer vision","Self-supervision","Meta-learning"], whyFit:"Strong computer-vision and deep-learning environment with dataset, benchmarking and evaluation work. It is more foundational than your MSc, but your empirical research record is relevant.", caution:"Requires two actual reference letters and independent questionnaire/coding tasks. The portal explicitly prohibits ChatGPT/LLM help on those tasks; complete them entirely yourself.", action:"Ask referees early if you want this. Do not start the coding task until the September applications are submitted.", documents:["CV","BSc and MSc certificates and transcripts","Two reference letters","Questionnaire answers completed independently without ChatGPT/LLMs","Coding-task solutions completed independently without ChatGPT/LLMs","Optional cloud link to theses/publications"], status:"Not started" },
  { id:"chalmers-foundation-model", title:"Doctoral Student in Physics-Guided Foundation Models for Time-Series", institution:"Chalmers University of Technology", country:"Sweden", deadline:"2026-10-01T23:59:00+02:00", deadlineLabel:"1 Oct 2026", window:"later", fit:7.7, funding:"Fully funded · 4 years · SEK 34,550/month", start:"Not stated", msc:"Master’s is listed as mandatory; no pending-completion wording is provided.", applyUrl:"https://academicpositions.com/ad/chalmers-university-of-technology/2026/doctoral-student-in-physics-guided-foundation-model-for-time-series-data/252448", source:"Official Chalmers vacancy mirrored by Academic Positions", tags:["Foundation models","Trustworthy AI","HPC","Time-series"], whyFit:"Your HPC, reproducible pipelines, systematic evaluation and reliable-AI work align unusually well. The gaps are time-series modelling, physics-informed ML and automotive systems.", caution:"Good secondary application, not a reason to delay DTU, ELLIS, Marburg or Luxembourg.", action:"Review after 21 September. If applying, centre the evidence-quality, reproducibility and safe-decision aspects of your work.", documents:["CV","Personal letter with introduction and motivation","Bachelor’s thesis","Master’s thesis if available","Academic transcripts","Reference contacts requested only after interview"], status:"Not started" },
  { id:"tum-formal-methods", title:"PhD Student — Fundamentals of Programming", institution:"Technical University of Munich", country:"Germany", deadline:null, deadlineLabel:"Rolling · review began 1 Sep 2026", window:"later", fit:5.8, funding:"Full-time university employment · typically TV-L E13", start:"As soon as possible or by agreement", msc:"Completed qualifying Master’s normally required for doctoral admission.", applyUrl:"https://www.cs.cit.tum.de/en/prog/open-positions/", source:"Official TUM Fundamentals of Programming Group page", tags:["Formal methods","Verification","AI","Programming languages"], whyFit:"There is a bridge through trustworthy AI, rule-based compliance and verification, but this is not your current research core. The group prioritises mathematical foundations, logic, automata and program analysis.", caution:"Do not present formal verification as an established passion. It is a lower-fit exploratory application.", action:"Hold until the high-fit applications are submitted. Apply only if you can write an honest research-interest bridge.", documents:["CV","Academic transcripts","Brief statement of research interests","Contact details of 2–3 references","All materials combined into one PDF and emailed"], status:"Not started" },
  { id:"mpi-cvml", title:"Direct PhD Application — Computer Vision and Machine Learning", institution:"Max Planck Institute for Informatics", country:"Germany", deadline:null, deadlineLabel:"Applications welcome year-round", window:"later", fit:9.0, funding:"Doctoral research route; confirm terms during selection", start:"Flexible", msc:"Qualified applicants invited; the direct-call page does not state pending-degree rules.", applyUrl:"https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/application/phd-applications", source:"Official Max Planck Institute for Informatics page", tags:["Computer vision","Vision-language","Generative models","Robustness"], whyFit:"High long-term fit across computer vision, vision-language, generative models, adversarial robustness and rigorous ML evaluation. It deserves a polished research statement, not a rushed application.", caution:"Rolling does not mean low priority forever. Prepare a strong research statement after the September deadline cluster.", action:"Target October. Select your strongest paper and build a focused research statement around multimodal evidence extraction and trustworthy visual AI.", documents:["CV","Research statement","Full publication list","List of referees","Most interesting research paper if applicable/allowed","Master’s and Bachelor’s transcripts","Preferably combine into one PDF and email"], status:"Not started" }
];

const masterDocuments = ["Academic CV tailored for PhD applications","BSc degree certificate","BSc full transcript","Current MSc transcript","MSc registration/enrolment proof","Official expected-completion or completion letter from UWC","One-page MSc thesis summary","Publication list with DOI and links","Google Scholar and ORCID links","GitHub profile with presentable research/code projects","Two or three referees who have agreed to be contacted","Master motivation-letter building blocks","Master research statement","Degree grading-scale explanation","Passport scan for later immigration/admin stages"];
const statusOptions: Status[] = ["Not started","Preparing","Ready","Submitted","Interview","Closed"];
const deadlineTime = (o:Opportunity) => o.deadline ? new Date(o.deadline).getTime() : Number.POSITIVE_INFINITY;
const daysRemaining = (d:string|null) => d ? Math.ceil((new Date(d).getTime()-Date.now())/86_400_000) : null;
const escapeCsv = (v:unknown) => `"${String(v??"").replaceAll('"','""')}"`;

export default function Home() {
  const [opportunities,setOpportunities]=useState<Opportunity[]>(seedOpportunities);
  const [checks,setChecks]=useState<Record<string,boolean>>({});
  const [search,setSearch]=useState("");
  const [fitFilter,setFitFilter]=useState("all");
  const [expanded,setExpanded]=useState<Record<string,boolean>>({"ku-leuven-compliance":true});
  const [dialogOpen,setDialogOpen]=useState(false);
  const [newOpportunity,setNewOpportunity]=useState({title:"",institution:"",country:"",deadline:"",url:""});
  const [hydrated,setHydrated]=useState(false);
  useEffect(()=>{try{const a=localStorage.getItem(STORAGE_KEY),b=localStorage.getItem(CHECK_KEY);if(a){const saved:Opportunity[]=JSON.parse(a);const savedById=new Map(saved.map(item=>[item.id,item]));const refreshed=SEED.map(item=>{const previous=savedById.get(item.id);return previous?{...item,status:previous.status,notes:previous.notes}:item});const custom=saved.filter(item=>!SEED.some(seed=>seed.id===item.id));setOpportunities([...refreshed,...custom]);}if(b)setChecks(JSON.parse(b));}catch{} setHydrated(true);},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(opportunities));},[hydrated,opportunities]);
  useEffect(()=>{if(hydrated)localStorage.setItem(CHECK_KEY,JSON.stringify(checks));},[checks,hydrated]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return [...opportunities].filter(i=>(!q||`${i.title} ${i.institution} ${i.country} ${i.tags.join(" ")}`.toLowerCase().includes(q))&&(fitFilter==="all"||i.fit>=Number(fitFilter))).sort((a,b)=>deadlineTime(a)-deadlineTime(b)||b.fit-a.fit)},[opportunities,search,fitFilter]);
  const submitted=opportunities.filter(i=>i.status==="Submitted"||i.status==="Interview").length;
  const urgent=opportunities.filter(i=>i.window==="urgent"&&i.status!=="Submitted").length;
  const highFit=opportunities.filter(i=>i.fit>=9).length;
  const documentProgress=masterDocuments.filter((_,i)=>checks[`master-${i}`]).length;
  const updateOpportunity=(id:string,patch:Partial<Opportunity>)=>setOpportunities(c=>c.map(i=>i.id===id?{...i,...patch}:i));
  function addOpportunity(){if(!newOpportunity.title.trim()||!newOpportunity.institution.trim())return;const d=newOpportunity.deadline?`${newOpportunity.deadline}T23:59:00Z`:null;setOpportunities(c=>[...c,{id:`custom-${Date.now()}`,title:newOpportunity.title.trim(),institution:newOpportunity.institution.trim(),country:newOpportunity.country.trim()||"To verify",deadline:d,deadlineLabel:newOpportunity.deadline||"To verify",window:"later",fit:0,funding:"To verify",start:"To verify",msc:"To verify",applyUrl:newOpportunity.url.trim()||"#",source:"Added manually — not yet verified",tags:["Needs research"],whyFit:"Not yet assessed.",caution:"Verify the official posting, deadline, funding and eligibility before applying.",action:"Research and score this opportunity.",documents:["Required documents to verify"],status:"Not started",custom:true}]);setNewOpportunity({title:"",institution:"",country:"",deadline:"",url:""});setDialogOpen(false)}
  function exportData(format:"json"|"csv"){const body=format==="json"?JSON.stringify({exportedAt:new Date().toISOString(),opportunities,checks},null,2):[["Institution","Position","Country","Deadline","Fit","Funding","Status","URL"].map(escapeCsv).join(","),...opportunities.map(i=>[i.institution,i.title,i.country,i.deadlineLabel,i.fit,i.funding,i.status,i.applyUrl].map(escapeCsv).join(","))].join("\n");const blob=new Blob([body],{type:format==="json"?"application/json":"text/csv"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`mayimunah-application-tracker.${format}`;a.click();URL.revokeObjectURL(url)}

  function OpportunityCard({item}:{item:Opportunity}){
    const isExpanded=expanded[item.id],remaining=daysRemaining(item.deadline),completed=item.documents.filter((_,i)=>checks[`${item.id}-${i}`]).length;
    return <article className="group overflow-hidden rounded-[1.35rem] border border-[var(--line)] bg-white shadow-[0_10px_40px_rgba(20,36,57,0.06)] transition hover:-translate-y-0.5 hover:shadow-[0_16px_48px_rgba(20,36,57,0.10)]">
      <div className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-2"><Badge className={item.fit>=9?"bg-[#163e5c] text-white":item.fit>=8?"bg-[#d9efe8] text-[#155348]":"bg-[#eef1f4] text-[#53606b]"}>{item.fit?`${item.fit.toFixed(1)}/10 fit`:"Unscored"}</Badge>{item.window==="urgent"&&<Badge className="bg-[#fff0e8] text-[#a44720]">Apply this week</Badge>}{!item.deadline&&<Badge variant="outline">Rolling</Badge>}</div><h3 className="max-w-3xl text-[1.16rem] font-semibold leading-snug text-[#13283a] sm:text-[1.28rem]">{item.title}</h3><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-[#607080]"><span className="font-medium text-[#334b5f]">{item.institution}</span><span className="inline-flex items-center gap-1"><MapPin className="size-3.5"/>{item.country}</span><span className="inline-flex items-center gap-1"><CalendarDays className="size-3.5"/>{item.deadlineLabel}</span></div></div><div className="flex shrink-0 flex-wrap items-center gap-2">{remaining!==null&&remaining>=0&&<span className={remaining<=4?"rounded-full bg-[#9d3520] px-3 py-2 text-sm font-semibold text-white":"rounded-full bg-[#edf3f7] px-3 py-2 text-sm font-semibold text-[#314f67]"}>{remaining===0?"Due today":`${remaining} day${remaining===1?"":"s"} left`}</span>}<Select value={item.status} onValueChange={v=>updateOpportunity(item.id,{status:v as Status})}><SelectTrigger className="w-[142px] border-[#ced8df] bg-white"><SelectValue/></SelectTrigger><SelectContent>{statusOptions.map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select></div></div>
      <div className="mt-4 flex flex-wrap gap-2">{item.tags.map(t=><span key={t} className="rounded-full bg-[#f2f5f6] px-2.5 py-1 text-xs font-medium text-[#536572]">{t}</span>)}</div>
      <div className="mt-5 grid gap-3 border-y border-[#e7ecef] py-4 sm:grid-cols-3"><div><p className="micro-label">Funding</p><p className="mt-1 text-sm font-medium text-[#243c4d]">{item.funding}</p></div><div><p className="micro-label">Start</p><p className="mt-1 text-sm font-medium text-[#243c4d]">{item.start}</p></div><div><p className="micro-label">Documents</p><p className="mt-1 text-sm font-medium text-[#243c4d]">{completed}/{item.documents.length} ready</p></div></div>
      <div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm leading-6 text-[#4e6372]"><span className="font-semibold text-[#1c3d54]">Next move:</span> {item.action}</p><div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" onClick={()=>setExpanded(c=>({...c,[item.id]:!isExpanded}))}>{isExpanded?<ChevronUp/>:<ChevronDown/>}{isExpanded?"Less":"Details"}</Button>{item.applyUrl!=="#"&&<Button asChild size="sm" className="bg-[#d96b3b] text-white hover:bg-[#bd5730]"><a href={item.applyUrl} target="_blank" rel="noreferrer">Open vacancy <ArrowUpRight/></a></Button>}</div></div></div>
      {isExpanded&&<div className="border-t border-[#dfe7eb] bg-[#f8fafb] p-5 sm:p-6"><div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="space-y-4"><section><p className="micro-label">Why it fits</p><p className="mt-2 text-sm leading-6 text-[#405766]">{item.whyFit}</p></section><section className="rounded-xl border border-[#f0d8ca] bg-[#fff8f4] p-4"><p className="flex items-center gap-2 text-sm font-semibold text-[#8b4326]"><CircleAlert className="size-4"/>Watch this</p><p className="mt-1.5 text-sm leading-6 text-[#6c4d3e]">{item.caution}</p></section><section><p className="micro-label">MSc timing</p><p className="mt-2 text-sm leading-6 text-[#405766]">{item.msc}</p></section></div><div><div className="mb-3 flex items-center justify-between"><p className="micro-label">Required document checklist</p><span className="text-xs font-semibold text-[#5d6f7b]">{completed}/{item.documents.length}</span></div><div className="space-y-2">{item.documents.map((d,i)=>{const k=`${item.id}-${i}`;return <label key={d} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[#dfe7eb] bg-white p-3 text-sm leading-5 text-[#344c5d] hover:border-[#b8c9d4]"><input type="checkbox" checked={Boolean(checks[k])} onChange={e=>setChecks(c=>({...c,[k]:e.target.checked}))} className="mt-0.5 size-4 accent-[#1b5b72]"/><span className={checks[k]?"text-[#72808a] line-through":""}>{d}</span></label>})}</div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label><span className="micro-label">Private notes</span><Textarea className="mt-2 min-h-20 border-[#ced8df] bg-white" value={item.notes??""} onChange={e=>updateOpportunity(item.id,{notes:e.target.value})} placeholder="Contacts, questions, draft status, portal notes…"/></label><a href={item.applyUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 pb-3 text-sm font-semibold text-[#1b5b72] hover:underline"><Link2 className="size-4"/>{item.source}</a></div></div>}
    </article>
  }
  const listForWindow=(w?:WindowName)=>filtered.filter(i=>!w||i.window===w);
  return <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><div className="top-rule"/><div className="mx-auto max-w-[1480px] px-4 pb-16 pt-6 sm:px-6 lg:px-8">
    <header className="mb-6 flex flex-col gap-5 rounded-[1.65rem] border border-[#dce5e9] bg-[#f9fbfb]/95 p-5 shadow-[0_18px_60px_rgba(21,45,61,0.08)] sm:p-7 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#c05a33]"><Target className="size-4"/>Application command centre</div><h1 className="font-display text-3xl font-semibold tracking-tight text-[#112c40] sm:text-4xl">Mayimunah’s 2026–27 opportunity tracker</h1><p className="mt-2 max-w-3xl text-[0.98rem] leading-6 text-[#587080]">Verified PhD and research opportunities, ordered by deadline and strategic fit. Research checked 2 September 2026.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>exportData("csv")}><Download/>CSV</Button><Button variant="outline" onClick={()=>exportData("json")}><Download/>Backup</Button><Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogTrigger asChild><Button className="bg-[#163e5c] text-white hover:bg-[#0d3049]"><Plus/>Add opportunity</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add an opportunity</DialogTitle><DialogDescription>Add the basics now. Unverified fields will be clearly marked for research.</DialogDescription></DialogHeader><div className="grid gap-3 py-2"><Input placeholder="Position title" value={newOpportunity.title} onChange={e=>setNewOpportunity({...newOpportunity,title:e.target.value})}/><Input placeholder="University or organisation" value={newOpportunity.institution} onChange={e=>setNewOpportunity({...newOpportunity,institution:e.target.value})}/><Input placeholder="Country" value={newOpportunity.country} onChange={e=>setNewOpportunity({...newOpportunity,country:e.target.value})}/><Input type="date" value={newOpportunity.deadline} onChange={e=>setNewOpportunity({...newOpportunity,deadline:e.target.value})}/><Input type="url" placeholder="Official vacancy URL" value={newOpportunity.url} onChange={e=>setNewOpportunity({...newOpportunity,url:e.target.value})}/></div><DialogFooter><Button onClick={addOpportunity}>Save opportunity</Button></DialogFooter></DialogContent></Dialog></div></header>
    <section className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{icon:Clock3,value:urgent,label:"applications due this week",tone:"coral"},{icon:Sparkles,value:highFit,label:"high-fit opportunities",tone:"blue"},{icon:Check,value:submitted,label:"submitted or interviewing",tone:"green"},{icon:FileCheck2,value:`${documentProgress}/${masterDocuments.length}`,label:"master documents ready",tone:"ink"}].map(({icon:Icon,value,label,tone})=><Card key={label} className={`metric-card metric-${tone}`}><CardContent className="flex items-center gap-4 p-5"><div className="metric-icon"><Icon/></div><div><p className="text-2xl font-bold tracking-tight">{value}</p><p className="text-sm opacity-80">{label}</p></div></CardContent></Card>)}</section>
    <section className="mb-6 grid gap-4 lg:grid-cols-[1.05fr_0.95fr]"><div className="rounded-[1.4rem] bg-[#153b56] p-5 text-white sm:p-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#a8d8d0]"><ListChecks className="size-4"/>This week · 2–5 September</div><h2 className="mt-3 font-display text-2xl font-semibold">Quality sprint: two core applications, one stretch</h2><ol className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><li className="action-step"><span>1</span><div><strong>KU Leuven first</strong><p>Update CV, attach transcript, write the personal half-page motivation, submit.</p></div></li><li className="action-step"><span>2</span><div><strong>Leiden second</strong><p>Confirm two referees, write the one-page motivation, submit.</p></div></li><li className="action-step"><span>3</span><div><strong>Oulu is the stretch</strong><p>Proceed only if the three-page research plan can be genuinely strong.</p></div></li></ol></div><div className="rounded-[1.4rem] border border-[#edd6c8] bg-[#fff8f3] p-5 sm:p-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#a5502d]"><CalendarDays className="size-4"/>Next week · 7–13 September</div><h2 className="mt-3 font-display text-2xl font-semibold text-[#4f2c20]">Marburg must be submitted before the weekend</h2><div className="mt-4 grid gap-2 text-sm text-[#6f4c3e]"><p><strong>Mon–Tue:</strong> Marburg motivation + CV tailoring.</p><p><strong>Wed:</strong> certificates/transcripts + portal review.</p><p><strong>Thu–Fri:</strong> submit Marburg; begin DTU and ELLIS supervisor research.</p><p><strong>Rolling slot:</strong> prepare Luxembourg World Models after Marburg is safe.</p></div></div></section>
    <Tabs defaultValue="urgent" className="gap-5"><div className="sticky top-0 z-20 -mx-1 flex flex-col gap-3 border-b border-[#dfe6ea] bg-[#f4f7f7]/95 px-1 py-3 backdrop-blur md:flex-row md:items-center md:justify-between"><TabsList className="h-auto w-full justify-start overflow-x-auto bg-[#e5ecef] p-1 md:w-auto"><TabsTrigger value="urgent" className="px-4 py-2">This week</TabsTrigger><TabsTrigger value="next" className="px-4 py-2">Next deadlines</TabsTrigger><TabsTrigger value="later" className="px-4 py-2">Later</TabsTrigger><TabsTrigger value="all" className="px-4 py-2">All</TabsTrigger><TabsTrigger value="documents" className="px-4 py-2">Document vault</TabsTrigger></TabsList><div className="flex w-full gap-2 md:max-w-[520px]"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#71808b]"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search topic, country or university" className="h-10 border-[#cbd7dd] bg-white pl-9"/></div><Select value={fitFilter} onValueChange={setFitFilter}><SelectTrigger className="h-10 w-[128px] border-[#cbd7dd] bg-white"><Filter className="size-4"/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All fits</SelectItem><SelectItem value="9">9+ fit</SelectItem><SelectItem value="8">8+ fit</SelectItem></SelectContent></Select></div></div>
    {(["urgent","next","later","all"] as const).map(tab=><TabsContent value={tab} key={tab} className="space-y-4">{listForWindow(tab==="all"?undefined:tab).map(i=><OpportunityCard item={i} key={i.id}/>)}{listForWindow(tab==="all"?undefined:tab).length===0&&<div className="rounded-2xl border border-dashed border-[#b8c7cf] p-10 text-center text-[#647582]">No opportunities match these filters.</div>}</TabsContent>)}
    <TabsContent value="documents"><section className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-[1.4rem] border border-[#d9e3e7] bg-white p-5 shadow-[0_12px_40px_rgba(20,36,57,0.06)] sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="micro-label">Reusable folder</p><h2 className="mt-1 font-display text-2xl font-semibold text-[#15364d]">Master document checklist</h2></div><Badge className="bg-[#d9efe8] text-[#155348]">{documentProgress}/{masterDocuments.length}</Badge></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{masterDocuments.map((d,i)=>{const k=`master-${i}`;return <label key={d} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[#e0e7ea] p-3 text-sm leading-5 text-[#344c5d] hover:bg-[#f7faf9]"><input type="checkbox" checked={Boolean(checks[k])} onChange={e=>setChecks(c=>({...c,[k]:e.target.checked}))} className="mt-0.5 size-4 accent-[#1b5b72]"/><span className={checks[k]?"text-[#7b878f] line-through":""}>{d}</span></label>})}</div></div><aside className="space-y-4"><div className="rounded-[1.4rem] bg-[#153b56] p-5 text-white sm:p-6"><p className="micro-label !text-[#a8d8d0]">Use this MSc wording</p><p className="mt-3 text-lg font-semibold leading-7">MSc Computer Science — expected academic completion in 2026; formal graduation ceremony in April 2027.</p><p className="mt-3 text-sm leading-6 text-[#d6e4eb]">Once UWC confirms completion, replace “expected academic completion” with the exact wording from the official completion letter.</p></div><div className="rounded-[1.4rem] border border-[#edd6c8] bg-[#fff8f3] p-5 sm:p-6"><p className="micro-label !text-[#a5502d]">Referee plan</p><ul className="mt-3 space-y-2 text-sm leading-6 text-[#654537]"><li>Ask 2–3 academics now for permission to list their details.</li><li>Only Bern needs two letters upfront among the current shortlist.</li><li>ELLIS contacts referees only for shortlisted candidates.</li><li>Never list someone who has not agreed.</li></ul></div></aside></section></TabsContent></Tabs>
    <footer className="mt-10 flex flex-col gap-2 border-t border-[#d9e2e6] pt-5 text-xs leading-5 text-[#6c7d88] sm:flex-row sm:justify-between"><p>Deadlines and requirements can change. Reopen the official vacancy before every submission.</p><p>Your edits are saved in this browser. Export a backup if you switch devices.</p></footer>
  </div></main>
}
